name: CI

on: [push, pull_request]

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v1
      - run: make build
      - run: make test-build
