name: CI

on: [push, pull_request]

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          bun-version: latest
      - run: make build
      - run: mak --completions fish
      - run: mak --file Makefile-examples/hello.Makefile --print-completion-targets
      - run: mak --file Makefile-examples/cubing.js.Makefile --print-graph
      - run: mak --file Makefile-examples/hello.Makefile
